---
title: "Knc_SampleList_master"
author: "Anne Fetrow"
date: "5/22/2019"
output: html_document
output: 
  html_document:
  css: stylesheet.css
  fig_caption: yes
  number_sections: yes
  toc: yes
  toc_float: yes
  toc_depth: 3
  code_folding: show
  df_print: paged
editor_options: console
---
#####Install new isoreader package
```{r install, eval = FALSE}
#devtools::install_github("KopfLab/isoreader")
#devtools::install_github("cubessil/isoprocessCUBES") #general CUBESsil lab stuff
#devtools::install_github("cubessil/Brettscustomfunctions") #only for processing clumped data
```
#####Load libraries
```{r setup, message=FALSE, warning=FALSE}
base.directory<-file.path("..") 

library(isoreader)
library(tidyverse)
library(isoprocessCUBES)
library(brettscustomfunctions)
library(rlang)
library(plotly)
library(RDocumentation)
library(tictoc)
```

```{r Read in SampleList}
Knc_Samples <- read.csv("Knc_SampleList_Master.csv")
```

```{r Merge SampleList and Geochem dataframes}


```

```{r Combining Sample info with Averaged Delta Geochem}
Knc_Samples_TS <- Knc_Samples %>% filter(Section != "DG")

Knc_DeltaGeochem_avg_20190523 <- read.csv("Knc_DeltaGeochem_avg_20190523")
Knc_DeltaGeochem_avg_20190523 <- Knc_DeltaGeochem_avg_20190523 %>% mutate(Sample_ID = Identifier1)
Knc_Samples_Deltageochem <- right_join(Knc_Samples_TS, Knc_DeltaGeochem_avg_20190523)
```

```{r Subsetting dataframes by Section}
Knc_TS2 <- Knc_Samples_Deltageochem %>% filter(Section == "TS2") #& Facies_ID == "Mp")
Knc_TS3 <- Knc_Samples_Deltageochem %>% filter(Section == "TS3")
Knc_TS4 <- Knc_Samples_Deltageochem %>% filter(Section == "TS4") 
Knc_TS5 <- Knc_Samples_Deltageochem %>% filter(Section == "TS5") 
```

```{r d13C vs Strat by Section}
d13C_TS2 <- Knc_TS2 %>% ggplot(aes(d13C.mean, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
                          geom_point()
d13C_TS2

d13C_TS3 <- Knc_TS3 %>% ggplot(aes(d13C.mean, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
                          geom_point()
d13C_TS3

d13C_TS4 <- Knc_TS4 %>% ggplot(aes(d13C.mean, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
                          geom_point()
d13C_TS4

d13C_TS5 <- Knc_TS5 %>% ggplot(aes(d13C.mean, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
                          geom_point()
d13C_TS5

d13C_all <- Knc_Samples_Deltageochem %>% ggplot(aes(d13C.mean, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
                          geom_point()
d13C_all
```
```{r d18O vs Strat by Section}
d18O_TS2 <- Knc_TS2 %>% ggplot(aes(d18O.mean, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
                          geom_point()
d18O_TS2

d18O_TS3 <- Knc_TS3 %>% ggplot(aes(d18O.mean, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
                          geom_point()
d18O_TS3

d18O_TS4 <- Knc_TS4 %>% ggplot(aes(d18O.mean, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
                          geom_point()
d18O_TS4

d18O_TS5 <- Knc_TS5 %>% ggplot(aes(d18O.mean, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
                          geom_point()
d18O_TS5

d18O_all <- Knc_Samples_Deltageochem %>% ggplot(aes(d18O.mean, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
                          geom_point()
d18O_all
```

```{r Strat Plotting}

Knc_Stratdistr <- Knc_Samples_TS %>% ggplot(aes(Facies_ID, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
      geom_point()
Knc_Stratdistr

TS2_faciesdistr <- Knc_TS2 %>% group_by(Facies_ID) %>% ggplot(aes(Facies_ID, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
      geom_point()
TS2_faciesdistr

TS4_faciesdistr <- Knc_TS4 %>% group_by(Facies_ID) %>% ggplot(aes(Facies_ID, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
      geom_point()
TS4_faciesdistr

TS3_faciesdistr <- Knc_TS3 %>% group_by(Facies_ID) %>% ggplot(aes(Facies_ID, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
      geom_point()
TS3_faciesdistr

TS5_faciesdistr <- Knc_TS5 %>% group_by(Facies_ID) %>% ggplot(aes(Facies_ID, Top_Height_m, color=Facies_ID, label=Sample_ID)) +
      geom_point()
TS5_faciesdistr

```
```{r Lateral Variation}
Lat_21.5m <- Knc_Samples_TS %>% filter(Section == "TS2-21.5")
Lateral_21.5 <- Lat_21.5m %>% ggplot(aes(Lateral_Distance_m, Facies_ID, color=Facies_ID, label=Sample_ID)) +
      geom_point()
Lateral_21.5

Lat_30m <- Knc_Samples_TS %>% filter(Section == "TS2-30")
Lateral_30 <- Lat_30m %>% ggplot(aes(Lateral_Distance_m, Facies_ID, color=Facies_ID, label=Sample_ID)) +
      geom_point()
Lateral_30

Lat_317m <- Knc_Samples_TS %>% filter(Section == "TS-317")
Lateral_317 <- Lat_317m %>% ggplot(aes(Lateral_Distance_m, Facies_ID, color=Facies_ID, label=Sample_ID)) +
      geom_point()
Lateral_317

Lat_323m <- Knc_Samples_TS %>% filter(Section == "TS-323")
Lateral_323 <- Lat_323m %>% ggplot(aes(Lateral_Distance_m, Facies_ID, color=Facies_ID, label=Sample_ID)) +
      geom_point()
Lateral_323
```
```{r Section Average Geochem Values}
#average d13Ccarb of each section

Geochem_sectionaverages <- Knc_Samples_Deltageochem %>% group_by(Section) %>%
                              summarise(
                                d13C_average = mean(d13C.mean),
                                d18O_average = mean(d18O.mean))
 

```
















EXTRA CODE THAT I MIGHT WANT LATER
# ```{r summarize data}
# #pulling corrected clumped data from Clumped Processing code
# correcteddata <- read.csv("ACF_alldata_brandfixed.csv")
# 
# justsamples <- correcteddata %>% filter(Type=="sample") %>% filter( Sample.ID != "MERCK")
# 
# avg_correcteddata <- correcteddata %>% filter(Type=="sample" & Sample.ID!= "MERCK") %>% group_by(Sample.ID) %>% summarise(
#     Replicates = n(),  
#     
#     d13C.stddev = sd(d13C, na.rm=TRUE),
#     d13C.stderr = d13C.stddev/sqrt(max(Replicates)),
#     d13C.PDB = mean(d13C), 
#     
#     d18O.SMOW.gas.stddev = sd(d18O.SMOW.gas, na.rm=TRUE),
#     d18O.SMOW.gas.stderr = d18O.SMOW.gas.stddev/sqrt(max(Replicates)),
#     d18O.SMOW.gas = mean(d18O.SMOW.gas), 
#     
#     d18O.VPDB.min.stddev = sd(d18O.VPDB.min, na.rm=TRUE),
#     d18O.VPDB.min.stderr = d18O.VPDB.min.stddev/sqrt(max(Replicates)),
#     d18O.VPDB.min = mean(d18O.VPDB.min), 
#     
#     D47.stddev = mean(ARF.D47stdcorr.pri.line, na.rm=TRUE),
#     D47.stderr = D47.stddev/sqrt(max(Replicates)),
#     D47.CDES = mean(ARF.D47stdcorr.pri.line), 
#     
#     ARF.Ghosh.temperature.stddev = sd(ARF.Ghosh.temp.pri.line), 
#     ARF.Ghosh.temperature.stderr = ARF.Ghosh.temperature.stddev/sqrt(max(Replicates)), 
#     ARF.Ghosh.temperature = mean(ARF.Ghosh.temp.pri.line),
#     
#     ARF.Bonifacie.temperature.stddev = sd(ARF.Bonifacie.temp.pri.line), 
#     ARF.Bonifacie.temperature.stderr = ARF.Bonifacie.temperature.stddev/sqrt(max(Replicates)), 
#     ARF.Bonifacie.temperature = mean(ARF.Bonifacie.temp.pri.line),
#     
#     d18O.water.stddev = sd(d18O.water.calc), 
#     d18O.water.stderr = d18O.water.stddev/sqrt(max(Replicates)), 
#     d18O.water = mean(d18O.water.calc)
#     
#     )
# 
#     #d45.stddev = sd(d45, na.rm=TRUE),
#     #d45 = mean(d45), 
#     #d46.stddev = sd(d46, na.rm=TRUE),
#     #d46 = mean(d46), 
#     #d47.stddev = sd(d47, na.rm=TRUE),
#     #d47 = mean(d47), 
#     #d48.stddev = sd(d48, na.rm=TRUE),
#     #d48 = mean(d48), 
#     #d49.stddev = sd(d49, na.rm=TRUE),
#     #d49 = mean(d49), 
#     #D47.stddev = mean(D47, na.rm=TRUE),
#     #D47 = mean(D47), 
#     #D48.stddev = sd(D48, na.rm=TRUE),    
#     #D48 = mean(D48), 
#     #D49.stddev = sd(D49, na.rm=TRUE),
#     #D49 = mean(D49),
#     #ARF.D47stdcorr.sec.allstds.stddev = sd(ARF.D47stdcorr.sec.allstds),
#     #ARF.D47stdcorr.sec.allstds = mean(ARF.D47stdcorr.sec.allstds), 
#     #ARF.Acid.corr.pri.defliese.stddev = sd(ARF.Acid.corr.pri.defliese),
#     #ARF.Acid.corr.pri.defliese = mean(ARF.Acid.corr.pri.defliese), 
#     #ARF.Acid.corr.pri.henkes.stddev = sd(ARF.Acid.corr.pri.henkes),
#     #ARF.Acid.corr.pri.henkes = mean(ARF.Acid.corr.pri.henkes)
#     #D47.stdev = sd(D47full),
#     #D47= mean(D47full),
#     #D47.se = D47.stdev/sqrt(max(n)),
# ```








